language: objective-c
osx_image: xcode611
xcode_workspace: AeroGearHttp.xcworkspace
xcode_scheme: AeroGearHttp
xcode_sdk: iphonesimulator

before_install:
    - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
